server:
  port: 8761
spring:
  application:
    name: eureka
  profiles:
    active: dev
eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: "http://${eureka.instance.hostname}:${server.port}/eureka/"
---
spring:
  config:
    activate:
      on-profile: dev
eureka:
  instance:
    hostname: localhost

---
spring:
  config:
    activate:
      on-profile: prod
eureka:
  instance:
    hostname: eureka